os: linux
dist: bionic
language: ruby
cache: bundler
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_acab821a6530_key -iv $encrypted_acab821a6530_iv
  -in pupperware-commercial-deploy-key.enc -out pupperware-commercial-deploy-key -d
- chmod 0400 pupperware-commercial-deploy-key
- eval "$(ssh-agent -s)"
- ssh-add pupperware-commercial-deploy-key
- bundle -v
- rm -f Gemfile.lock
- "# Update system gems if requested. This is useful to temporarily workaround troubles
  in the test runner"
- "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f
  for an example of how this was used"
- "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
- '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
- gem --version
- bundle -v
script: |
  echo helloworld
  git clone git@github.com:puppetlabs/pupperware-commercial.git
  cd pupperware-commercial
  docker-compose up -d
  healthy=0
  while [ $healthy -lt 6 ]; do docker ps --all && healthy=`docker ps --no-trunc -a --format '{{ json . }}' | jq '{status: .Status}' | grep healthy | wc -l` && sleep 20; done
  docker-compose exec puppet puppet agent -t
bundler_args: "--without system_tests"
rvm:
- 2.5.7
stages:
- static
- spec
- if: tag =~ ^v\d
  name: deploy
jobs:
  fast_finish: true
  include:
  - env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file
      rubocop syntax lint metadata_lint"
    stage: static
branches:
  only:
  - master
  - "/^v\\d/"
notifications:
  email: false
